language: java

script: mvn package

addons:
  artifacts: true
  s3_region: "ap-northeast-1"

env: ARTIFACTS_KEY=AKIAJZC4E2J6ZULEZZ7Q ARTIFACTS_SECRET=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 ARTIFACTS_BUCKET=doim-editor-test
